apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-tracker-config
data:
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "admin1234"
  MYSQL_HOST: "mysql-db"
