-- SQL delta schema changes for Google AI / Gemini Ecosystem
-- Target Database: ai_tools_news_db
USE ai_tools_news_db;

-- 1. Insert Google AI Tools
INSERT INTO ai_tools (name, category, description, website_link, chatbot_link, playground_link, api_docs_link, pricing, features, tags, popularity_score, community_rating, github_link) VALUES
('Gemini App', 'LLMs', 'Google consumer conversational AI app powered by Gemini models, offering multimodal understanding, reasoning, and planning.', 'https://gemini.google.com', 'https://gemini.google.com', NULL, NULL, 'FREEMIUM', 'Multimodal, Extensions (Workspace/YouTube), Advanced reasoning, Image generation', 'google,gemini,llm,chatbot', 9.6, 4.6, NULL),
('Gemini API', 'LLMs', 'Developer API endpoint to access Google’s state-of-the-art multimodal Gemini models with massive context windows.', 'https://ai.google.dev', NULL, 'https://aistudio.google.com', 'https://ai.google.dev/docs', 'FREEMIUM', 'Function calling, System instructions, Structured outputs, High context window', 'google,gemini,api,developer', 9.5, 4.7, 'https://github.com/google-gemini'),
('Google AI Studio', 'AI Development', 'A web-based prototyping environment by Google for developers to experiment with Gemini models and export code in multiple languages.', 'https://aistudio.google.com', NULL, 'https://aistudio.google.com', 'https://ai.google.dev/docs', 'FREE', 'Quick prompting, System instructions parameter, Temperature tuner, Easy SDK code export', 'google,aistudio,prototyping,developer', 9.4, 4.8, NULL),
('Vertex AI', 'AI Deployment', 'Google Cloud’s unified AI platform offering enterprise tools to train, evaluate, tune, and deploy generative AI models.', 'https://cloud.google.com/vertex-ai', NULL, NULL, 'https://cloud.google.com/vertex-ai/docs', 'PAID', 'Model tuning (LoRA), Vector Search, Feature store, Pipeline orchestration, Enterprise security', 'google,vertex,deployment,enterprise,cloud', 9.2, 4.4, NULL),
('NotebookLM', 'AI Productivity', 'A personalized AI collaborator by Google that uses your own documents to generate summaries, study guides, and audio podcasts.', 'https://notebooklm.google.com', 'https://notebooklm.google.com', NULL, NULL, 'FREE', 'Source-grounded answers, Audio Overviews (podcasts), Study guides, Citation links', 'google,notebooklm,productivity,rag', 9.7, 4.9, NULL),
('Gemma', 'LLMs', 'A family of lightweight, state-of-the-art open-weights models built by Google from the same research and technology used to create Gemini.', 'https://ai.google.dev/gemma', NULL, NULL, 'https://ai.google.dev/gemma/docs', 'FREE', 'Open-weights, Local hosting, Quantization compatible, Lightweight and fast', 'google,gemma,opensource,llm,local', 9.3, 4.7, 'https://github.com/google/gemma_pytorch'),
('Imagen', 'AI Image Generation', 'Google’s advanced text-to-image diffusion model delivering high-fidelity photorealistic images and text rendering.', 'https://deepmind.google/technologies/imagen-3', NULL, NULL, 'https://cloud.google.com/vertex-ai/generative-ai/docs/image/overview', 'PAID', 'Photorealistic detail, High-quality text rendering, Aspect ratio control', 'google,imagen,image-gen,diffusion', 9.1, 4.5, NULL),
('Veo', 'AI Video Generation', 'Google’s most capable generative video model, producing high-definition video in diverse cinematic styles from text prompts.', 'https://deepmind.google/technologies/veo', NULL, NULL, 'https://cloud.google.com/vertex-ai/generative-ai/docs/video/overview', 'PAID', 'High-definition 1080p, Cinematic controls, Creative consistency', 'google,veo,video-gen,diffusion', 9.2, 4.6, NULL),
('Lyria', 'AI Audio Generation', 'Google DeepMind’s music generation model designed to create high-quality audio tracks with vocals and instrumentals.', 'https://deepmind.google/technologies/lyria', NULL, NULL, NULL, 'PAID', 'Vocal synthesis, Instrumental tracks, Watermarked output (SynthID)', 'google,lyria,audio-gen,music', 8.8, 4.3, NULL),
('DeepMind AlphaFold', 'AI Biology', 'An AI system developed by Google DeepMind that predicts 3D structure and biomolecular interactions of proteins, DNA, and RNA.', 'https://deepmind.google/alphafold-3', NULL, 'https://alphafoldserver.com', 'https://github.com/google-deepmind/alphafold3', 'FREE', 'Biomolecular modeling, DNA/RNA interactions, High accuracy structure prediction', 'google,deepmind,alphafold,biology,science', 9.9, 4.9, 'https://github.com/google-deepmind/alphafold3'),
('Gemini CLI / Antigravity', 'Developer Tools', 'A fast, command-line interface and developer agent for interacting with the Google Gemini API directly from the terminal.', 'https://github.com/google-gemini/gemini-cli', NULL, NULL, NULL, 'FREE', 'Shell execution, Auto code completions, File pipeline uploads', 'google,gemini,cli,terminal,antigravity', 9.0, 4.5, 'https://github.com/google-gemini/gemini-cli')
ON DUPLICATE KEY UPDATE description=VALUES(description), website_link=VALUES(website_link), pricing=VALUES(pricing), popularity_score=VALUES(popularity_score);

-- 2. Insert Google AI news
INSERT INTO news_articles (title, summary, ai_summary, source, category, published_date, article_link, tags, author, ai_company, sentiment, popularity_score, trending_score) VALUES
('Google DeepMind Launches Gemini 1.5 Flash for High-Speed Multimodal Efficiency', 'Google has announced Gemini 1.5 Flash, a lightweight model optimized for high-volume, low-latency, and cost-effective deployment with a 1-million token context window.', 'Google released Gemini 1.5 Flash, setting a new benchmark for low-latency multimodal reasoning. It is designed to be highly cost-efficient and is available immediately in Google AI Studio.', 'Google AI Blog', 'Google AI updates', DATE_SUB(NOW(), INTERVAL 1 DAY), 'https://blog.google/technology/ai/gemini-1.5-flash', 'google,gemini,flash,release,aistudio', 'Google Editors', 'Google AI', 'POSITIVE', 9.4, 9.6),
('Google Announces Gemini Omni (GPT-4o Competitor) with Real-Time Video Interaction', 'During the Google I/O developer conference, Google previewed Gemini Omni, demonstrating native real-time conversation utilizing live video feed from smart glasses and mobile cameras.', 'Google introduced Gemini Omni (Project Astra prototypes), showcasing real-time audio and video conversation. The model accepts visual camera inputs and responds vocally with zero lag.', 'Google Developers Blog', 'Google I/O announcements', DATE_SUB(NOW(), INTERVAL 3 DAY), 'https://developers.googleblog.com/gemini-omni-io', 'google,gemini,omni,io,multimodal', 'I/O Reporter', 'Gemini', 'POSITIVE', 9.7, 9.8),
('Google Search Rolls Out AI Overviews Globally, Transforming Search Engine Landscape', 'Google has officially launched AI Overviews in search results, leveraging a customized Gemini model to summarize complex queries and link relevant sources.', 'Google Search upgraded with AI Overviews. Using a tailored Gemini model, it synthesizes search answers and displays them directly at the top of query results, changing organic SEO paradigms.', 'Google AI Blog', 'Google Search AI changes', DATE_SUB(NOW(), INTERVAL 6 DAY), 'https://blog.google/products/search/ai-overviews-rollout', 'google,search,overview,gemini', 'Search Team', 'Google AI', 'NEUTRAL', 9.3, 9.1),
('DeepMind Releases AlphaFold 3, Modeling Complex Molecular Assemblies', 'Google DeepMind has published details of AlphaFold 3, predicting structures of proteins, DNA, RNA, and chemical compounds with high precision, accelerating drug discovery.', 'AlphaFold 3 extends structural prediction to DNA, RNA, and chemical ligands. This enables deep insight into biological processes and accelerates pharmaceutical research.', 'DeepMind Blog', 'DeepMind research papers', DATE_SUB(NOW(), INTERVAL 10 DAY), 'https://deepmind.google/blog/alphafold-3-release', 'google,deepmind,alphafold,biology', 'Science Editor', 'DeepMind', 'POSITIVE', 9.8, 9.5),
('Google Cloud Vertex AI Integrates Gemma 2 Open Models for Enterprise Deployment', 'Google has integrated Gemma 2 models (9B and 27B) into Vertex AI, offering optimized serving pipelines and one-click deployment for enterprises.', 'Google added Gemma 2 (9B and 27B) to Vertex AI Model Garden. Enterprises can now deploy, evaluate, and fine-tune Gemma 2 models using Google Cloud infrastructure.', 'Google Cloud AI Blog', 'Vertex AI announcements', DATE_SUB(NOW(), INTERVAL 15 DAY), 'https://cloud.google.com/blog/vertex-ai-gemma2', 'google,vertex,gemma,cloud', 'Cloud Team', 'Google AI', 'POSITIVE', 9.0, 8.8),
('Antigravity: Google Developers Unveil Next-Gen Autonomous AI Coding Agent', 'Google Developers have showcased Antigravity, an open-source autonomous coding agent that hooks into the Gemini API to execute complex file refactoring and database migrations.', 'Google Developers released Antigravity, an autonomous developer agent. Hooked into Gemini API, it solves code tasks, manages dependencies, and runs terminal compilations independently.', 'Google Developers Blog', 'Gemini agentic AI updates', DATE_SUB(NOW(), INTERVAL 20 DAY), 'https://developers.googleblog.com/antigravity-agent', 'google,gemini,antigravity,agent,coding', 'Dev Team', 'Gemini', 'POSITIVE', 9.5, 9.7)
ON DUPLICATE KEY UPDATE summary=VALUES(summary), ai_summary=VALUES(ai_summary);
